name: Build and deploy Agenda to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-agenda-app-name
  REGISTRY_LOGIN_SERVER: your-registry.azurecr.io
  IMAGE_NAME: agenda-api
  AGENDA_DOCKERFILE: 'Agenda/Agenda.Api/Dockerfile'
  AGENDA_BUILD_CONTEXT: 'Agenda'
  DEPLOYMENT_ENVIRONMENT_NAME: Development

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared/build-and-deploy-dotnet-webapp.yml
    with:
      dockerfile: ${{ env.AGENDA_DOCKERFILE }}
      build_context: ${{ env.AGENDA_BUILD_CONTEXT }}
      image_name: ${{ env.IMAGE_NAME }}
      registry_login_server: ${{ env.REGISTRY_LOGIN_SERVER }}
      azure_webapp_name: ${{ env.AZURE_WEBAPP_NAME }}
      environment_name: ${{ env.DEPLOYMENT_ENVIRONMENT_NAME }}
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      azure_webapp_publish_profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_AGENDA }}
