services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
      POSTGRES_DB: event
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  agenda-postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: agenda
      POSTGRES_PASSWORD: agenda
      POSTGRES_DB: agenda
    ports:
      - "5433:5432"
    volumes:
      - agenda-postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  agenda-postgres-data:
