name: Build and deploy EventServiceApi to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-events-app-name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: Release
  EVENTSERVICEAPI_PROJECT_PATH: 'EventService/EventServiceApi/EventServiceApi.csproj'
  DEPLOYMENT_ENVIRONMENT_NAME: Development

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared/build-and-deploy-dotnet-webapp.yml
    with:
      dotnet_version: ${{ env.DOTNET_VERSION }}
      project_path: ${{ env.EVENTSERVICEAPI_PROJECT_PATH }}
      build_configuration: ${{ env.BUILD_CONFIGURATION }}
      azure_webapp_name: ${{ env.AZURE_WEBAPP_NAME }}
      azure_webapp_package_path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      environment_name: ${{ env.DEPLOYMENT_ENVIRONMENT_NAME }}
    secrets:
      azure_webapp_publish_profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
