<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Event.Domain\Event.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Event.Domain.Event" Alias="DomainEvent" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
