name: Build and deploy BFF to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-bff-app-name
  REGISTRY_LOGIN_SERVER: your-registry.azurecr.io
  IMAGE_NAME: bff-api
  BFF_DOCKERFILE: 'Bff/Bff.Api/Dockerfile'
  BFF_BUILD_CONTEXT: 'Bff'
  DEPLOYMENT_ENVIRONMENT_NAME: Development

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared/build-and-deploy-dotnet-webapp.yml
    with:
      dockerfile: ${{ env.BFF_DOCKERFILE }}
      build_context: ${{ env.BFF_BUILD_CONTEXT }}
      image_name: ${{ env.IMAGE_NAME }}
      registry_login_server: ${{ env.REGISTRY_LOGIN_SERVER }}
      azure_webapp_name: ${{ env.AZURE_WEBAPP_NAME }}
      environment_name: ${{ env.DEPLOYMENT_ENVIRONMENT_NAME }}
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      azure_webapp_publish_profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BFF }}
