name: Build and deploy BFF to Azure Container Apps

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-dotnet-webapp.yml
    with:
      dockerfile: Bff/Bff.Api/Dockerfile
      build_context: Bff
      image_name: bff-api
      registry_login_server: eventagendaregistry.azurecr.io
      acr_name: eventagendaregistry
      container_app_name: bff
      resource_group: event-agenda-project
      key_vault_name: event-agenda-kv
      environment_name: Development
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
