name: Build and deploy BFF to Azure Container Apps

on:
  push:
    branches: [ "master" ]
    paths:
      - "Bff/**"
      - ".github/workflows/build-bff.yml"
      - ".github/workflows/build-and-deploy-dotnet-webapp.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-dotnet-webapp.yml
    with:
      dockerfile: Bff/Bff.Api/Dockerfile
      build_context: Bff
      dotnet_test_path: Bff/Bff.sln
      image_name: bff-api
      registry_login_server: eventagendaregistry.azurecr.io
      acr_name: eventagendaregistry
      container_app_name: bff
      resource_group: event-agenda-project
      key_vault_name: event-agenda-kv
      environment_name: development
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
