name: Build and deploy EventServiceApi to Azure Container Apps

env:
  CONTAINER_APP_NAME: events
  RESOURCE_GROUP: event-agenda-project
  REGISTRY_LOGIN_SERVER: eventagendaregistry.azurecr.io
  ACR_NAME: eventagendaregistry
  KEY_VAULT_NAME: event-agenda-kv
  IMAGE_NAME: event-api
  EVENT_DOCKERFILE: 'Event/Event.Api/Dockerfile'
  EVENT_BUILD_CONTEXT: 'Event'
  DEPLOYMENT_ENVIRONMENT_NAME: Development

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-dotnet-webapp.yml
    with:
      dockerfile: ${{ env.EVENT_DOCKERFILE }}
      build_context: ${{ env.EVENT_BUILD_CONTEXT }}
      image_name: ${{ env.IMAGE_NAME }}
      registry_login_server: ${{ env.REGISTRY_LOGIN_SERVER }}
      acr_name: ${{ env.ACR_NAME }}
      container_app_name: ${{ env.CONTAINER_APP_NAME }}
      resource_group: ${{ env.RESOURCE_GROUP }}
      key_vault_name: ${{ env.KEY_VAULT_NAME }}
      environment_name: ${{ env.DEPLOYMENT_ENVIRONMENT_NAME }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
